### ISSUE TITLE
update gitlab within the container

### ISSUE THREAD

**Issue by rddaz2013** [qnap-dev/container-apps#36]
How to update an old Gitlab 8.1.3 on the latest version without losing data?

TS-453 Pro

**Comment by e1ee1e11** [comment]
Hi

The latest version of [sameersbn/gitlab](https://hub.docker.com/r/sameersbn/gitlab/tags/) is 8.12.6.
Please follow the steps to upgrade gitlab manually.

Step 1. SSH into your NAS

```
$ ssh admin@NAP_IP
```

Step 2. Change directory to gitlab folder

```
# cd /share/CACHEDEV1_DATA/.qpkg/container-station/data/application/gitlab
```

Step 3. Edit docker-compose.yml file

```
postgresql:
  restart: always
  image: sameersbn/postgresql:9.4-23
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
gitlab:
  restart: always
  image: sameersbn/gitlab:8.12.6
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=false
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
redis:
  restart: always
  image: sameersbn/redis:latest
  command:
    - --loglevel warning
```

Step 4. Use compose to recreate app

```
# docker-compose up -d
```

Wait for a moment and check your data on the website.

I hope that helps clarify the issue. Let me know if you need additional information.

**Comment by rddaz2013** [comment]
thx 

works fine
