### ISSUE TITLE
Wizards documentation

### ISSUE THREAD

**Issue by davidkudera** [qnap-dev/container-apps#41]
Hello,

I just got my new qnap NAS which I choose specifically because of support for containers, VMs and other similary cool things. In my work I'm used to install any service/app on our servers I want and so I have plenty ideas of what I would also like to see on my personal NAS at home.

Is there for example some complete documentation of wizards? Or maybe even some complete manual? I belive that there would be more applications available with some easily accessible documentation.

Thank you

**Comment by WebDucer** [comment]
I also need the documentation of the wizards to be able to customize the docker-compose.yaml configurations (ports, environment variables, volumes, etc).

It would be perfect to be able to validate the own wizards without push the whole configuration and test it on the NAS for every little change (try and error).

**Comment by fcwu** [comment]
@e1ee1e11 may u publish dockerized QPKG document, which includes wizards format?
I think we should finalize https://qnap-dev.github.io/container-station-api/dqpkg.html soon.

**Comment by e1ee1e11** [comment]
Hi @davidkudera,  @WebDucer 

The wizard format of Container Station is wirted in "Setup Wizard" paragraph in [Other files under shared/](https://qnap-dev.github.io/container-station-api/dqpkg.html#other-files-under-shared) section.
We comply with JSON Schema to design wizard format. 
To see the detail information, please refer to http://json-schema.org/

**Comment by davidkudera** [comment]
Hi, that looks good I think. Thank you :+1:
