### ISSUE TITLE
Feature Request: Workflow for updating image (or settings) used for a container

### ISSUE THREAD

**Issue by anjos** [qnap-dev/container-apps#58]
In Container Station, the web-based GUI does not provide a simple way to edit settings of any created container. While this works fine when images are kind of well understood and easy instructions exist to set them up, it does not work very well when one is experimenting/developing new images.

Some of the settings are changeable once the container is created. For example "CPU", "Memory" or "Auto-start" seem to be editable. It would be really useful if these edition capabilities were extended to the whole set of information concerning a container: the image used, the environment variables, the volumes that can be mounted, etc. A restart would then be required for changes to take effect.

This feature would allow one to experiment and adjust the use of containers through the web interface without the need to SSH into the machine, which will help on the usability of Container Station.

As of today, the only solution the user has (apart from SSH'ing into the machine as I saw in other threads) is to destroy and re-do the container from scratch, which is quite tedious.

**Comment by ColinHuang** [comment]
Currently we only provide settings to modify Auto-start/CPU/Memory/Network mode/device. And the modified container will not use the original image name.

In fact, the Docker container does not provide an easy way for the user to reset the settings. Therefore, we recommend that if you want to modify more settings, you can re-create the container.
