### ISSUE TITLE
Logo proposal for app

### ISSUE THREAD

**Issue by stefanycesar** [qnap-dev/container-apps#67]
Hello, I'm designer😊. I want to know if you agree than I contribute to your project.
I think than you idea is amazing and will looks great with a face. 😎

**Comment by QNAP-Demo** [comment]
Hi @stefanycesar,

Please feel free to contribute if you want :)

**Comment by walkerlee** [comment]
Hi @stefanycesar,

Please feel free to contribute if you want :)
